### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Siflei** [joetimmerman/garmin-connect-export#3]
I'm getting the following error when calling the script:

Traceback (most recent call last):
  File "gcexport.py", line 135, in <module>
    hostname_url = http_req('http://connect.garmin.com/gauth/hostname')
  File "gcexport.py", line 112, in http_req
    response = opener.open(request, data=post)  # This line may throw a urllib2.HTTPError.
  File "C:\ED\Python\Python3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\ED\Python\Python3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\ED\Python\Python3\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "C:\ED\Python\Python3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\ED\Python\Python3\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\ED\Python\Python3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\ED\Python\Python3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\ED\Python\Python3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\ED\Python\Python3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\ED\Python\Python3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

http://connect.garmin.com/gauth/hostname is not found and results in a 404.

Probably Garmin changed something.

Simon

**Comment by Siflei** [comment]
It's fixed here:
https://github.com/pe-st/garmin-connect-export

**Comment by joetimmerman** [comment]
Thanks, getting everything updated to play nicely with Garmin is on my to-do list.
